name: Welcome
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: behaviorbot/welcome@v1.4.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
